### ISSUE TITLE
Twitter Card用の画像

### ISSUE THREAD

**Issue by tererun** [Purajuku/purajuku_web#10]
## 事象

Twitter Cardの画像が表示されていない

## スクリーンショット

<img width="602" alt="image" src="https://user-images.githubusercontent.com/27857171/171976646-8691807c-3e2e-4d9e-9a3a-9393e777492c.png">

**Comment by graycat27** [comment]
Facebookの[シェアデバッガー](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Ftwitter.com%2FPurajuku%2Fstatus%2F1532917192970227717)ではちゃんと通ってるように見える。
Twitterも同じ `og:image` のメタタグを参照してると思うんだけども…
![image](https://user-images.githubusercontent.com/64903817/171992123-bb457ecc-6d19-46fe-bc79-0bcbe0c727bb.png)

**Comment by graycat27** [comment]
Facebookのシェアデバッガでは正常に画像が取得できているように見える…。
![image](https://user-images.githubusercontent.com/64903817/171992161-236ec635-3455-4b36-8fb8-1824b02748fe.png)

**Comment by graycat27** [comment]
Twitterのデバッガで確認したら、だめっぽいわね https://cards-dev.twitter.com/validator
![image](https://user-images.githubusercontent.com/64903817/171992231-d63f7d3b-24ea-402d-b101-70d4a7e26e5b.png)

**Comment by tererun** [comment]
Twitterは独自のカードがあるらしく、それを設定しないといけないみたいです。うわ～ん

**Comment by graycat27** [comment]
(記事ページ)[https://purajuku.dev/about/server-plugin/]覗いたけどmetaタグ不足…？
![image](https://user-images.githubusercontent.com/64903817/171992334-2dab2326-44ed-4ec0-a1df-b329e1cd490f.png)

**Comment by tererun** [comment]
React Helmet面倒だからよくわからんで通してる
